In [1]:
def daq_sql_connection_local(verbose=False):
    import mysql.connector
    import os
    try:
        connection = mysql.connector.connect(
          host='localhost',
          user=os.environ['MYSQL_USER'],
          password=os.environ['MYSQL_PASSWORD'],
          database=os.environ['MYSQL_DATABASE'],
          port=3306
        )
        if verbose: print(connection)
        return connection
    except:
        return False

In [2]:
from optparse import OptionParser
import os,sys
import datetime
import numpy as np
import cygno as cy
import time
import midas
import midas.client
import gzip

In [22]:
import pandas as pd

In [6]:
verbose=True

In [23]:
connection = daq_sql_connection_local(verbose)#cy.daq_sql_cennection(verbose)
if not connection:
    print('{:s} ERROR: Sql connetion'.format(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")))

<mysql.connector.connection.MySQLConnection object at 0x7f0ddee9ac40>

In [31]:
table_name = "Runlog"
row_element = "run_number"
row_element_condition = str(11020)

import datetime
sql = "SELECT * FROM `"+table_name+"` WHERE `"+row_element+"` > "+row_element_condition+";"
#SELECT * FROM `Runlog` WHERE `run_number` = 1024;
if verbose: print(sql)

SELECT * FROM `Runlog` WHERE `run_number` > 11020;

In [34]:
sql_query = pd.read_sql_query (sql, connection)

/home/standard/.local/lib/python3.8/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [35]:
df = pd.DataFrame(sql_query)

In [36]:
df

,run_number,run_description,start_time,exposure_sec,GEM3_V,GEM2_V,GEM1_V,T2_V,T1_V,DRIFT_V,...,total_gas_flow,stop_time,number_of_events,storage_local_status,storage_cloud_status,storage_tape_status,file_size,file_checksum,file_s3_tag,online_reco_status
0,11021,"S003:DATA:Fe, 4cm Cu shielding, Fe 17-18, Trg:...",2023-03-02 06:41:33,0.3,420.0,420.0,420.0,500.0,500.0,996.0,...,20.0,2023-03-02 06:42:23,83.0,1,1,-1,328439132,199aa4bea48deb5129a95ab68581ae00,LNGS,-1
1,11022,"S003:DATA:Fe, 4cm Cu shielding, Fe 17-18, Trg:...",2023-03-02 06:42:35,0.3,420.0,420.0,420.0,500.0,500.0,996.0,...,20.0,2023-03-02 06:43:28,86.0,1,1,-1,341245192,dcc68fcb47a41e4c396cccd7742b32ad,LNGS,-1
2,11023,"S003:DATA:Fe, 4cm Cu shielding, Fe 17-18, Trg:...",2023-03-02 06:43:39,0.3,420.0,420.0,420.0,500.0,500.0,996.0,...,20.0,2023-03-02 06:44:32,85.0,1,1,-1,337916044,f5697904f8026fdea4aebfdad977ceb7,LNGS,-1
3,11024,"S003:DATA:Fe, 4cm Cu shielding, Fe 17-18, Trg:...",2023-03-02 06:44:43,0.3,420.0,420.0,420.0,500.0,500.0,996.0,...,20.0,2023-03-02 06:45:31,81.0,1,1,-1,318393293,f90183b3b6e38492cea8bbd31ff18a65,LNGS,-1
4,11025,"S003:PED:Fe, closed shielding, Fe 17-18, veto ...",2023-03-02 06:46:13,0.3,420.0,420.0,420.0,500.0,500.0,996.0,...,20.0,2023-03-02 06:47:09,104.0,1,1,-1,375273849,9defc5bd8cf29e43f8262376a55920bc,LNGS,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,11270,"S003:PED:Fe, closed shielding, Fe 17-18, veto ...",2023-03-06 09:36:33,0.3,420.0,420.0,420.0,500.0,500.0,996.0,...,20.0,2023-03-06 09:37:30,105.0,1,1,-1,378951170,f04659b62b077a1c6289e997c931aecb,LNGS,-1
248,11271,"S003:DATA:Fe, 4cm Cu shielding, Fe 17-18, Trg:...",2023-03-06 09:39:27,0.3,420.0,420.0,420.0,500.0,500.0,996.0,...,20.0,2023-03-06 09:43:29,403.0,1,1,-1,1588941420,789b32e77ed67414ec1569297bd7768a,LNGS,-1
249,11272,"S003:DATA:Fe, 4cm Cu shielding, Fe 17-18, Trg:...",2023-03-06 09:53:31,0.3,420.0,420.0,420.0,500.0,500.0,996.0,...,20.0,2023-03-06 09:57:36,405.0,1,1,-1,1605995330,e3bf266f71098c8d5c5c243806b1fda1,LNGS,-1
250,11273,"S003:DATA:Fe, 4cm Cu shielding, Fe 17-18, Trg:...",2023-03-06 10:07:38,0.3,420.0,420.0,420.0,500.0,500.0,996.0,...,20.0,2023-03-06 10:11:42,405.0,1,-1,-1,1600935223,444b3f221c8de6b1792afe6de2f528cb,None,-1
251,11274,"S003:DATA:Fe, 4cm Cu shielding, Fe 17-18, Trg:...",2023-03-06 10:21:44,0.3,420.0,420.0,420.0,500.0,500.0,996.0,...,20.0,NaT,NaN,-1,-1,-1,-1,None,None,-1

In [38]:
df.to_csv('./test_local.csv', index = False)